# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbe9bb66c52e0d8b14a5f7caba532f99a8cf1c334b5a4750ef9d760320f314742a7c487f8c1dc7750a9b5096d951392ab90ee12a7cfb7efc25490ae25ae08457

test:
  secret_key_base: bef9474d6e46fec326a494c061c98b102bab05e0075eeb2237b722583c0a6cd03421990fd40b877e20cebe77378e5a09035fd7e1b9a663b42ff42b8657493aa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
